## The disk file
apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata: 
  name: localdisk 
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true


## PersistentVolume
kind: PersistentVolume 
apiVersion: v1 
metadata: 
   name: host-pv 
spec: 
   storageClassName: localdisk
   persistentVolumeReclaimPolicy: Recycle 
   capacity: 
      storage: 1Gi 
   accessModes: 
      - ReadWriteOnce 
   hostPath: 
      path: /var/output


## PersistentVolumeClaim
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
   name: host-pvc 
spec: 
   storageClassName: localdisk 
   accessModes: 
      - ReadWriteOnce 
   resources: 
      requests: 
         storage: 100Mi


## A Pod That Uses a PersistentVolume for Storage
apiVersion: v1 
kind: Pod 
metadata: 
   name: pv-pod 
spec: 
   containers: 
       - name: busybox 
         image: busybox 
         command: ['sh', '-c', 'while true; do echo Success! > /output/success.txt; sleep 5; done'] 
         volumeMounts: 
            - name: pv-storage 
              mountPath: /output 
   volumes: 
      - name: pv-storage 
         persistentVolumeClaim: 
            claimName: host-pvc
      